### ISSUE TITLE
wooting_analog_plugin unable to read product and manufacturer strings

### ISSUE THREAD

**Issue by Garbius** [WootingKb/wooting-analog-plugin#5]
I've been working with @simon-wh on Discord to figure out what's going on with my Wooting Two. When running `WootingAnalogSDK.Initialise()`, the SDK panics because it is unable to read product, manufacturer, and sometimes serial strings from the keyboard. I have attached logs with `RUST_BACKTRACE="full"` and `RUST_LOG="debug"` enabled. One is from [when it was able to read the serial number](https://github.com/WootingKb/wooting-analog-plugin/files/4968237/with_serial.txt) and the other [when it wasn't](https://github.com/WootingKb/wooting-analog-plugin/files/4968236/no_serial.txt). The occurence of the two seems to be random, weighted towards the latter.

@simon-wh compiled a special sauce wooting_analog_sdk that doesn't crash and burn when the strings can't be read and that makes it initialize as expected.

Moreover, the analog functionality sometimes ceases to function completely, including DirectInput and Xinput. This too seems to occur randomly and can usually be helped by rebooting. Whether it is related or not is unknown to me.

I can arrange a bare metal machine running live boot Linux with the keyboard connected that you'll be able to access through a VPN if you would like to debug it hands-on.

Firmware 1.29.2 (also tested on 1.29.1)
wootility 3.5.12-beta
wooting_analog_sdk and wooting_analog_plugin compiled 2020-02-04 (not the special sauce version)

**Comment by simon-wh** [comment]
Hmmm, I'm still really unsure as to why this is occurring. Especially inconsistently. I had another look into it, as I remember you mentioning how Wootility has no issue obtaining the serial. That's likely down to the fact that Wootility pulls in the Serial over the USB interface we use for configuration, not from the information the OS provides about the HID device (which is how this plugin does it). 

> I can arrange a bare metal machine running live boot Linux with the keyboard connected that you'll be able to access through a VPN if you would like to debug it hands-on.

That could be helpful in the future. However, right now I'm more curious if you're able to see this behaviour on Linux as well as Windows, that would help determine where the issue lies, hardware/firmware or OS/software. 

 > Moreover, the analog functionality sometimes ceases to function completely, including DirectInput and Xinput. This too seems to occur randomly and can usually be helped by rebooting. Whether it is related or not is unknown to me.

This is quite weird. Is it only helped by a PC(?) reboot or does replugging the keyboard help at all? The former would potentially indicate to me a OS/software issue, as replugging the keyboard I think should have the same effect as you're fully cycling the keyboard.

Also, when you say "analog functionality" is this just DirectInput + XInput or including the Analog SDK when you're using the "special sauce version"?

@PastaJ36 May be able to help give some more insight

**Comment by Rocky04** [comment]
@Garbius I just overfly the issue and haven't even looked into the new SDK at all but I think the issue is most likely related to dead Win device entries. On Win there is a composite device entry and all the interfaces are sub devices like child elements of that. It can rarely happen that such a child element lost the connection to the root element and so Win creates another element for that interface. Maybe this happens if a sub device of the Wooting was manually disabled and so that Win had created a new entry for that. So that there is maybe a dead element present causing problems.

If that is the case a device wipe should fix it: https://wooting.helpscoutdocs.com/article/73-guide-flush-all-dead-registry-entries


_I assume the SDK also uses HIDAPI and so rely on the enumeration from Win and so the data in the Registry..._

**Comment by Garbius** [comment]
@Rocky04 I've tested that without success. I have, however, narrowed it down to it being a Windows-related issue. I set up a clean Windows 10 install on another computer and it worked fine. I would prefer not to reformat this computer, and so the quest continues. 

The Xinput functionality has now completely ceased to function, which makes it significantly easier to reproduce. The Xbox 360 Wireless Receiver device is detected by windows and the device shows up in the game controller list, but no buttons or axes are responding to input. 

I have tried purging everything related to Wooting, including wootility, wooting analog plugin, wooting analog sdk, the registry keys above, similar keys in `HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\Joystick\OEM` and then fixed the joystick calibration with the registry script. All that with appropriate reboots.

Any other ideas?

**Comment by Rocky04** [comment]
@Garbius I don't think the mixed-up joystick IDs are related to your problem that you sometimes can't detect the IDs of the Wooting interfaces at all. You should not see the entries for the keyboard interfaces and only the data for the Xbox controller interface can maybe have missing data (for sure the serial number is missing for it).

The troubleshooting about the Xbox controller part should be done in Discord anyway and I think it has nothing to do with your initial problem. In short I assume you have a Ryzen system. The USB ports which are handled directly from the CPU typically have problems with the XInput interface of the Wooting. So you should use ports which are handled by the chipset.

**Comment by Garbius** [comment]
I had completely forgotten about this post. @Rocky04 seems to be onto something. I had tested multiple ports and apparently managed to hit CPU controlled ports, despite trying ports that were not in the same "cluster". I figured out which ports weren't controlled by the CPU and it now initializes properly. Thank you for the help.

**Comment by Rocky04** [comment]
You are welcome...

Unfortunately I can't tell what's causing the underlying issue because I don't have access to a Ryzen system and won't have anytime soon. So I'm not able to check it out.

**Despite I think this is an underestimated problem because Ryzen systems are on the rise and the issue isn't obvious to find out. The support for this problem on Discord isn't really helpful because they only mention the standard phrase to try out different ports, if any.**
